spring:
  profiles:
    active: local
  kafka:
    consumer:
        bootstrap-servers: confluent-kafka-cluster1-cp-kafka:9092
        key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group-id: group1
